# Generated by Django 4.1.4 on 2022-12-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('age', models.CharField(blank=True, max_length=60, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('pendant', 'pendant'), ('princess', 'princess'), ('choker', 'choker'), ('collar', 'collar'), ('opera', 'opera'), ('charm', 'charm'), ('matinée', 'matinée'), ('multi-chain', 'multi-chain'), ('locket', 'locket')], max_length=300)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('out_stock', 'out_stock'), ('out_of_order', 'out_of_order')], max_length=150, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Necles.customer')),
                ('iteam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Necles.necklace')),
                ('tag', models.ManyToManyField(to='Necles.tag')),
            ],
        ),
        migrations.AddField(
            model_name='necklace',
            name='tag',
            field=models.ManyToManyField(to='Necles.tag'),
        ),
    ]
