# Generated by Django 4.1.4 on 2022-12-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Necles', '0002_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
    ]
