# Generated by Django 4.1.4 on 2022-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Necles', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='imge',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
